### ISSUE TITLE
URGENT: Fetching of `GB/T 16159-2012` when resource unavailable will crash process

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-gb#32]
Relaton should never crash due to network unavailability.

```
275 fetching GB/T 16159-2012...
276 #<Thread:0x000055605fda1820@/usr/local/bundle/gems/relaton-bib-0.4.1/lib/relaton_bib/workers_pool.rb:17 run> terminated with exception (report_on_exception is true):
277 /usr/local/lib/ruby/2.6.0/net/http.rb:949:in `rescue in block in connect': Failed to open TCP connection to openstd.samr.gov.cn:80 (Connection timed out - connect(2) for "openstd.samr.gov.cn" port 80) (Errno::ETIMEDOUT)
278 	from /usr/local/lib/ruby/2.6.0/net/http.rb:946:in `block in connect'
279 	from /usr/local/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
```

**Comment by andrew2net** [comment]
@ronaldtse the `RelatonBib::RequestError` error class is caught in `relaton`.
When a flavor gem return `nil` it means a document not found then `relaton` save `not_found` in its cache. But if a flavor gem raise a `RequestError` the `relaton` catches it and doesn't save any files.
Since all flavor gems return a document or `nil` we need somehow notify `relaton` when there is a network issue. If we need to change this logic we have to change the return format in all flavor gems.

**Comment by ronaldtse** [comment]
I encountered that problem in Metanorma. @opoudjis should we catch network issues at Relaton or Metanorma?

**Comment by andrew2net** [comment]
The exception should be caught in the `relaton` gem. Could you tell me how to reproduce this error in Metanorma?

**Comment by andrew2net** [comment]
@ronaldtse I checked it. I was wrong, the exception is caught in `relaton-cli`. So if you use `relaton` directly you have to catch the `RelatonBib::RequestError` exception.
In `relaton-cli` it is:
```
      def fetch_document(code, options)
        if registered_types.include?(options[:type])
          doc = Cli.relaton.fetch(code, options[:year]&.to_s)
          doc ? doc.to_xml : "No matching bibliographic entry found"
        end
      rescue RelatonBib::RequestError => e
        e.message
      end
```

**Comment by opoudjis** [comment]
I already catch the error in Metanorma, in metanorma-standoc/lib/asciidoctor/standoc/ref.rb, fetch_ref():

````
rescue RelatonBib::RequestError
        warn "Could not retrieve #{code}: no access to online site"
        nil
````

Please don't catch it in relaton.

**Comment by andrew2net** [comment]
@opoudjis we don't catch it in relaton, we catch it in relaton-cli only
